### PR TITLE
New terminology

### PR DESCRIPTION
**Pull request by schickling**
With many terminology changes being introduced in [https://github.com/graphcool/graphcool](graphcool/graphcool), `graphcool-lib` also needs to be updated.

The following library changes have been introduced:

- [ ] Rename `projectId` to `serviceId`
- [ ] Rename `pat` to `rootToken`
- [ ] Rename `generateUserToken` to `generateNodeToken`
- [ ] Add `createSchema(): Promise<GraphQLSchema>` to simplify API gateway code (cc @nikolasburk)

### Changes required from the backend

- [ ] Implement and pass in [temporary root token](https://github.com/graphcool/graphcool/issues/740) as `rootToken` in event context as documented in https://github.com/graphcool/graphcool/issues/219#issuecomment-334938777
- [ ] Deprecate `pat` in event context (this is purely a documentation/communication change)
- [ ] Deprecate `generateUserToken` mutation
- [ ] Introduce new `generateNodeToken` mutation with the following schema:

```graphql
      mutation {
        generateNodeToken(input: {
          rootToken: "${this.rootToken}"
          serviceId: "${this.serviceId}"
          nodeId: "${nodeId}", 
          modelName: "${typeName}",
          expirationInSeconds: Int
          clientMutationId: "static"
        }) {
          token
        }
      }
```

### Notes

- Be careful when introducing breaking changes since the current function runtime (being based on Auth0 Extend) always pulls in the latest version of a package, so a redeploy of a function could break a customer's app
- Consider bumping the version count to `1.x` (see prev point)
- When merging this please add an extensive README & release notes

### CODE REVIEW

**Comment by kbrandwijk** [comment]
You have kept the `tokenOrRootToken` method, but at the same time, the rename caused the behavior to change, and a single token to be used.

`fromEvent` used to set the pat (now `rootToken`), `api()` used to set to `token` when specified in the options. I proposed going forward with one token, but then the `tokenOrRootToken` method is no longer needed.

**Comment by kbrandwijk** [comment]
Another question: can you restructure the code so the new `createSchema` method goes into a different class? Because now whenever you require `graphcool-lib`, you're also pulling all these extra dependencies in (`apollo-link-http`, `graphql`, `graphql-tools`), making this lightweight module a lot heavier then it needs to be, because the `createSchema` functionality is very specific, and will never be used in functions.

**Comment by kbrandwijk** [comment]
I like the fact that parameter naming is consistent now. Just `token`. However, as `generateNodeToken` specifically requires a rootToken, there should be an additional check to see if the provided token is a rootToken or not.

**Comment by kbrandwijk** [comment]
The release notes don't mention the biggest breaking change: having to specify endpoints manually outside resolver functions!

**Comment by mwickett** [comment]
@kbrandwijk Can you elaborate on that change?

**Comment by kbrandwijk** [comment]
@mwickett Yes, I created https://github.com/graphcool/graphcool-lib/issues/14 for it, but it is already fixed by @timsuchanek.

**Pull request merged**
